/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.web.bind.annotation.RestController;


@SpringBootApplication
public class App {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(App.class,args);

        System.out.println("Loaded controllers:");
        String[] beanNames = context.getBeanNamesForAnnotation(RestController.class);
        for (String name : beanNames) {
            System.out.println(" -> " + name);
        }
    }
}
